import { describe, expect, test } from 'bun:test'
import { metaHead, relayHead, sentHead } from '../src/envelope'
import { cut, plain } from '../src/fmt'

const ESC = ''

// The shapes are transcribed from real records (the 2026-09-02 index): a
// relay from the `lore` session to `ccc`, a task notification, the two-record
// slash command, and the `/model` echo that carries terminal color codes.

describe('relayHead', () => {
  const REAL = `Another Claude session sent a message:
<cross-session-message from="uds:/tmp/cc-socks/32093.sock" from-name="lore" from-mode="prompting">
Kickoff brief from lore for ccc v0 — canon is in your repo at commit 90eb9a7.
</cross-session-message>

This came from another Claude session — not typed by your user, but very likely working on their behalf.`

  test('keeps the message, drops the socket and the standing trailer', () => {
    expect(relayHead(REAL)).toEqual({
      from: 'lore',
      text: 'Kickoff brief from lore for ccc v0 — canon is in your repo at commit 90eb9a7.',
    })
  })

  // 96 characters of envelope before the first word: the whole point.
  test('the envelope cost more than the head a spine row can show', () => {
    expect(cut(REAL, 80).startsWith('Another Claude session sent a message')).toBe(true)
    expect(cut(relayHead(REAL).text, 80)).toBe('Kickoff brief from lore for ccc v0 — canon is in your repo at commit 90eb9a7.')
  })

  // A long relay can be cut before its closing tag; the body is still there.
  test('survives a truncated close', () => {
    const t = '<cross-session-message from-name="ccc" from-mode="prompting">\nMaster defect handled: hotfix-gridbuilder branched'
    expect(relayHead(t)).toEqual({ from: 'ccc', text: 'Master defect handled: hotfix-gridbuilder branched' })
  })

  test('a record that is not an envelope passes through', () => {
    expect(relayHead('just words')).toEqual({ from: null, text: 'just words' })
  })
})

describe('metaHead', () => {
  test('a slash command is its name and args', () => {
    expect(metaHead('<command-name>/loop</command-name>\n<command-message>loop</command-message>\n<command-args>5m /babysit</command-args>')).toEqual({
      tag: 'command',
      text: '/loop 5m /babysit',
    })
    expect(metaHead('<command-name>/clear</command-name>\n<command-args></command-args>')).toEqual({ tag: 'command', text: '/clear' })
  })

  test('a task notification is its summary, not its ids', () => {
    const t = `<task-notification>
<task-id>af80d234d489e766f</task-id>
<tool-use-id>toolu_0184jdynpG1aXAyP4jWLdZjP</tool-use-id>
<output-file>/private/tmp/claude-501/-Users-rf-studio-code-fun-ccc/b3919c35/tasks/af80d234d489e766f.output</output-file>
<status>completed</status>
<summary>Agent "Metal cell-grid renderer + glyph atlas" finished</summary>
<result>Done. The Metal cell-grid renderer is in and green.</result>
</task-notification>`
    expect(metaHead(t)).toEqual({ tag: 'task', text: 'Agent "Metal cell-grid renderer + glyph atlas" finished' })
  })

  test('the local-command caveat carries nothing the command row does not', () => {
    expect(metaHead('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>')).toEqual({
      tag: 'caveat',
      text: '',
    })
  })

  test('command stdout loses its terminal colors', () => {
    expect(metaHead(`<local-command-stdout>Set model to ${ESC}[1mFable 5${ESC}[22m and saved as your default</local-command-stdout>`)).toEqual({
      tag: 'stdout',
      text: 'Set model to Fable 5 and saved as your default',
    })
    expect(metaHead('<local-command-stdout>(no content)</local-command-stdout>')).toEqual({ tag: 'stdout', text: '' })
  })

  test('a skill body is the skill', () => {
    expect(metaHead('Base directory for this skill: /Users/rf-studio/.claude/skills/html-artifacts\n\n# HTML artifacts\n\nMarkdown is the default.')).toEqual({
      tag: 'skill',
      text: 'html-artifacts',
    })
  })

  test('an image is its file', () => {
    expect(metaHead('[Image: source: /Users/rf-studio/Desktop/Screenshot 2026-06-30 at 12.14.46 AM.png]')).toEqual({
      tag: 'image',
      text: 'Screenshot 2026-06-30 at 12.14.46 AM.png',
    })
  })

  test('an interrupt, a reminder, a context report', () => {
    expect(metaHead('[Request interrupted by user]')).toEqual({ tag: 'interrupted', text: '' })
    expect(metaHead('[Request interrupted by user for tool use]')).toEqual({ tag: 'interrupted', text: 'for tool use' })
    expect(metaHead('<system-reminder>\nThe user named this session "space".\n</system-reminder>')).toEqual({
      tag: 'reminder',
      text: 'The user named this session "space".',
    })
    expect(metaHead('## Context Usage\n\n**Model:** claude-fable-5  \n**Tokens:** 26.2k / 900k (3%)\n\n### Estimated usage')).toEqual({
      tag: 'context',
      text: 'claude-fable-5 · 26.2k / 900k (3%)',
    })
  })

  test('an unrecognised injection is itself, with no tag', () => {
    expect(metaHead('Continue from where you left off.')).toEqual({ tag: null, text: 'Continue from where you left off.' })
  })
})

describe('sentHead — the outbound half', () => {
  const FULL = JSON.stringify({
    to: 'ccc',
    summary: 'Ack ccc v0 ledger, banked + verified',
    message: 'v0 ledger banked in the wiki (0bfdc95) — every relayed number verified here.',
  })

  test('names the recipient and the sender\'s own one-line summary', () => {
    expect(sentHead(FULL)).toEqual({ to: 'ccc', summary: 'Ack ccc v0 ledger, banked + verified' })
  })

  // The one that matters: an instruction's input reaches the page already cut
  // to `head` characters, so any relay long enough to be worth reading does
  // NOT parse as JSON. A first pass at this read the fields off the parsed
  // object and was dead code on every real message.
  test('reads a message truncated before its closing brace', () => {
    expect(sentHead(FULL.slice(0, 70))).toEqual({ to: 'ccc', summary: 'Ack ccc v0 ledger, banked + verified' })
    // Cut inside the summary itself: the recipient still survives.
    expect(sentHead(FULL.slice(0, 40)).to).toBe('ccc')
  })

  test('falls back to the message when there is no summary', () => {
    expect(sentHead('{"to":"lore","message":"corpus is green"}')).toEqual({ to: 'lore', summary: 'corpus is green' })
  })

  test('escaped quotes in a summary survive the fallback', () => {
    const t = '{"to":"ccc","summary":"the \\"localtime\\" split","message":"…'
    expect(sentHead(t)).toEqual({ to: 'ccc', summary: 'the "localtime" split' })
  })

  test('a call that is not a relay yields nothing to show', () => {
    expect(sentHead('{"pattern":"foo"}')).toEqual({ to: null, summary: null })
    expect(sentHead('not json at all')).toEqual({ to: null, summary: null })
  })
})

test('plain strips only the escape sequences', () => {
  expect(plain(`${ESC}[1mbold${ESC}[0m [brackets] stay`)).toBe('bold [brackets] stay')
})
